name: Pipeline DevOps - CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🟢 Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependencias backend
        run: |
          cd backend
          npm install

      - name: 🚦 Verificar servidor backend (lint/test futuro)
        run: |
          cd backend
          echo "Servidor verificado para pipeline inicial" 