name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install deps
      run: npm ci

    - name: Lint (ejemplo)
      run: npx eslint . || true 

    - name: Run tests
      run: npm test

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build backend image
      run: docker build -t mi-backend-app ./backend 