name: Pipeline DevOps – CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v3

      - name: 🟢 Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Instalar dependencias en backend
        working-directory: backend
        run: npm install

      - name: 🧪 Ejecutar pruebas Jest
        working-directory: backend
        run: npx jest 