name: Pipeline DevOps – CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ir a la carpeta backend
        working-directory: ./backend
        run: echo "Nos movemos al backend"

      - name: Instalar dependencias
        working-directory: ./backend
        run: npm install

      - name: Ejecutar tests
        working-directory: ./backend
        run: npm test 